### ISSUE TITLE
Number of jumps divided by 4?

### ISSUE THREAD

**Issue by cviebrock** [pahefu/pilgrimstarpath#5]
On https://github.com/pahefu/pilgrimstarpath/blob/master/js/gdl.js#L396 you divide the hyperdrive distance (e.g. 1600) by 4.

```js
common.destinations[i].jumps = Math.ceil(distance/(common.jumpRange/4.0));
```

What's the reasoning here?  If something is 16,000 LY away, and I can go 1,600LY per jump, it should be approximately 10 jumps away, not 40, right?

**Comment by pahefu** [comment]
Because distance between systems,blackhole jumped distance and hyperdrive max jump distance are expressed in "linear distance", which a by 4 factor of math euclidean distance.

DTC value is right and equivalent to math value.

it is checked with pen & paper, noting that each xyz unit equals 100years.

**Comment by pahefu** [comment]
Because distance between systems, distance jumped after a blackhole, and hyperdrive max distance are expressed in "linear distance", which is a by-4 factor from euclidean math distance between two 3d points in space.

DTC is right, and matches the euclidean maths.

It's checkable on pen & paper (and a calculator), if you take in account that per each unit in XYZ you have 100 ly of real math distance.

That's a very old question explained (better said, tried to be explained) on reddit, because it seems a Patch 1.00 / 1.03 effect after the prerelease leak guy traveled to the center so fast. Ergo the true reasoning for using the x4 values is up to HG.

Of course we can be wrong and it can be a math problem, but that seems unlikely when all euclidean maths with coordinates seem to match.

**Comment by cviebrock** [comment]
Thanks for the explanation.  After reading a bunch of posts, I think a better explanation is that it's a "fudge factor" they added to the game to make it slower to travel via hyper-jumps.

I know they explain it like the difference between flying New York to L.A. vs driving ... however you'd need to be a really bad navigator to take a path 4 times longer between two points in 3D space. ;)

Thanks!
